### PR TITLE
NXP-26864: nuxeo-duoweb-authentication package includes too many jars already provided by the default Nx server

### PR DESCRIPTION
**Pull request by RSalem07**

### CODE REVIEW

**Comment by troger** [comment]
I would go for a simpler commit message such as "NXP-26864: fix nuxeo-duoweb-authentication package"

While cleaning up the MP, could you also remove the unneeded property `<nuxeo.distribution.version>11.1-SNAPSHOT</nuxeo.distribution.version>` in the parent `pom.xml` (already defined with the pom inheritance).

**Comment by troger** [comment]
:+1:

**Review by ffjdm — CHANGES_REQUESTED** [review]
Please exclude the pom.xml file in `./install/bundles/pom.xml` using `<artifact type="pom" />`

**Review by ffjdm — APPROVED** [review]

**Comment by ffjdm** [comment]
👍

**Comment by RSalem07** [comment]
- Remove pom.xml from bundles was already done
- I would go for a simpler commit message such as "NXP-26864: fix nuxeo-duoweb-authentication package" ; => **i will do it on the rebase/stash comment, if it's ok for you.**
- remove the unneeded `<nuxeo.distribution.version>11.1-SNAPSHOT</nuxeo.distribution.version>` from pom.xml parent => **Done**

**Comment by ffjdm** [comment]
👍

**Comment by troger** [comment]
:+1:

**Comment by troger** [comment]
:+1:

**Pull request merged**
